spring.application.name=App_01_Spring_JDBCTemplate


spring.datasource.url=jdbc:postgresql://localhost:5432/sb01
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=org.postgresql.Driver