spring.application.name=App_02_CRUDRepo


spring.datasource.url=jdbc:postgresql://localhost:5432/sb01
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update